ZCS-11169 : Log4j upgrade version to 2.17.1 changes
Zimbra/zm-selenium pull request #292
Opened 2022-04-26 06:31 UTC by abhishekdeshmukh2209

Issue :- Upgrade Log4j version to 2.17.1

2022-04-26 09:31 UTC, preshitaagrawal commented on src/java/com/zimbra/qa/selenium/framework/core/ExecuteHarnessMain.java
> +				        LoggerContext context = (LoggerContext) LogManager.getContext(false);
please check indentation

2022-04-26 22:52 UTC, abhishekdeshmukh2209 commented on src/java/com/zimbra/qa/selenium/framework/core/ExecuteHarnessMain.java
> +				        LoggerContext context = (LoggerContext) LogManager.getContext(false);
done please check.

2022-04-28 04:29 UTC, preshitaagrawal commented on src/java/com/zimbra/qa/selenium/framework/core/ExecuteHarnessMain.java
> +        Configurator.setLevel(LogManager.getLogger(ExecuteHarnessMain.class).getName(), Level.INFO);
incorrect indentation

2022-04-28 04:47 UTC, zimsuchitgupta requested changes

2022-04-28 04:47 UTC, zimsuchitgupta commented on conf/log4j.properties
> +log4j.logger.testcase.trace=TRACE, A3
To define a logger below are the steps :
logger.{name}.name = fully classified class name/ package name/ category name/ unique name
logger.{name}.level = info/warn etc
logger.{name}.additivity = false
logger.{name}.appenderRef.{refname}.ref = {appenderRef}

2022-04-28 04:47 UTC, zimsuchitgupta commented on conf/log4j.properties
> +appender.A1.layout.type=PatternLayout
You also have to provide appender name like
appender.A1.name = STDOUT

2022-04-28 04:47 UTC, zimsuchitgupta commented on conf/log4j.properties
> +rootLogger.level = WARN
also define a default appender to rootLogger. 
rootLogger.appenderRef.stdout.ref = STDOUT

2022-04-28 12:39 UTC, zimsuchitgupta requested changes

2022-04-28 12:39 UTC, zimsuchitgupta commented on conf/log4j.properties
> +appender.A3.type=org.apache.log4j.RollingFileAppender
Use RollingFile only as org.apache.log4j.RollingFileAppender is belongs to log4j-1.2.16

2022-04-28 12:39 UTC, suchitgupta11 commented on conf/log4j.properties
> +appender.A2.type=org.apache.log4j.RollingFileAppender
Use RollingFile only as org.apache.log4j.RollingFileAppender is belongs to log4j-1.2.16

2022-04-28 12:39 UTC, zimsuchitgupta commented on conf/log4j.properties
> +appender.general.type=org.apache.log4j.RollingFileAppender
Use RollingFile only as org.apache.log4j.RollingFileAppender is belongs to log4j-1.2.16

2022-04-28 12:39 UTC, zimsuchitgupta commented on conf/log4j.properties
> +appender.general.layout=org.apache.log4j.PatternLayout
Use PatternLayout only as org.apache.log4j.PatternLayout is belongs to log4j-1.2.16, Please correct for other places too.

2022-04-28 12:39 UTC, zimsuchitgupta commented on conf/log4j.properties
> +logger.A5.appenderRef.stdout.ref = A1
Remove this line, as no appender defined as A1.

2022-04-28 12:39 UTC, zimsuchitgupta commented on conf/log4j.properties
> +logger.A5.appenderRef.stdout.ref = A1
Remove this line, as no appender defined as A1

2022-04-28 12:39 UTC, zimsuchitgupta commented on conf/log4j.properties
> +logger.A5.appenderRef.stdout.ref = A1
Remove this line, as no appender defined as A1

2022-04-28 12:39 UTC, zimsuchitgupta commented on conf/log4j.properties
> +appender.coverage.layout=org.apache.log4j.PatternLayout
Use PatternLayout only as org.apache.log4j.PatternLayout is belongs to log4j-1.2.16.

2022-04-28 12:39 UTC, zimsuchitgupta commented on conf/log4j.properties
> +appender.sleep.layout=org.apache.log4j.PatternLayout
Use PatternLayout only as org.apache.log4j.PatternLayout is belongs to log4j-1.2.16,

2022-04-28 12:56 UTC, zimsuchitgupta approved these changes

2022-04-28 13:20 UTC, preshitaagrawal approved these changes

2022-05-16 13:11 UTC, dasiyogesh commented on ivy.xml
> +               <dependency org="org.apache.logging.log4j" name="log4j-api" rev="2.17.1" />
indentation not right

2022-05-16 13:21 UTC, abhishekdeshmukh2209 commented on ivy.xml
> +               <dependency org="org.apache.logging.log4j" name="log4j-api" rev="2.17.1" />
corrected.

2022-05-16 13:44 UTC, dasiyogesh commented on src/java/com/zimbra/qa/selenium/framework/core/ExecuteHarnessMain.java
> +                                       Logger openQABasePackage = LogManager.getLogger(OpenQABasePackage);
indentation incorrect

2022-05-16 13:44 UTC, dasiyogesh commented on src/java/com/zimbra/qa/selenium/framework/core/ExecuteHarnessMain.java
> +			        Configurator.setLevel(LogManager.getRootLogger().getName(), Level.INFO);
indentation incorrect

2022-05-16 13:45 UTC, dasiyogesh commented on src/java/com/zimbra/qa/selenium/framework/core/ExecuteHarnessMain.java
> +                Configurator.setLevel(LogManager.getLogger(ExecuteHarnessMain.class).getName(), Level.INFO);
indentation incorrect

2022-05-16 13:45 UTC, dasiyogesh commented on src/java/com/zimbra/qa/selenium/framework/util/ZimbraAccount.java
> +		 Configurator.setLevel(LogManager.getRootLogger().getName(), org.apache.logging.log4j.Level.INFO);
indentation off

2024-09-29 04:17 UTC, closed without merging